### ISSUE TITLE
Allow some parameters to be specified to the stack

### ISSUE THREAD

**Issue by ninadsp** [SathyaBhat/folding-aws#2]
For other people to consume this project, it makes sense to convert the following into parameters that can be specified to the cdk app by the user:

* AMI ID for the F@H VM
* Region to set up the VPC and ASG stacks in 
* name of the SSH key
* Maximum acceptable spot price
* IP address that is allowed SSH access to the instances in the ASG

**Comment by SathyaBhat** [comment]
I agree.. we could also have auto-spot pricing but fetching the current spot prices, add couple of cents and ask if that is ok - though this would be better off as a separate issue/enhancement

**Comment by ninadsp** [comment]
I think the ASG size should also be configurable, if someone wishes to donate more compute power.

**Comment by SathyaBhat** [comment]
I agree

**Comment by ninadsp** [comment]
Filed #8 for the spot pricing bit. Closing this issue as all other parameters on this issue have been covered.
